# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use official Node.js LTS Alpine base image
FROM node:lts-alpine AS builder

# Create app directory
WORKDIR /usr/src/app

# Install dependencies and build
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src
RUN npm install --ignore-scripts && npm run build

# Runtime image
FROM node:lts-alpine
WORKDIR /usr/src/app

# Copy built files and install production deps
COPY --from=builder /usr/src/app/build ./build
COPY package.json package-lock.json ./
RUN npm install --production --ignore-scripts && npm cache clean --force

# Use stdio transport for MCP
ENTRYPOINT ["node", "build/index.js"]
